/* This file is generated by scripts/process-messages/index.js. Do not edit! */

/**
 * %file% does not exist
 * @param {{ "file": string }} values
 * @returns {never}
 */
export function app_template_missing(values) {
	const error = new Error(
		`${'app_template_missing'}\n${`${values.file} does not exist`}\nhttps://next.svelte.dev/e/@sveltejs/kit/${'app_template_missing'}`
	);
	error.name = 'SvelteKit error';
	throw error;
}

/**
 * %file% is missing %tag%
 * @param {{ "file": string; "tag": string }} values
 * @returns {never}
 */
export function app_template_tag_missing(values) {
	const error = new Error(
		`${'app_template_tag_missing'}\n${`${values.file} is missing ${values.tag}`}\nhttps://next.svelte.dev/e/@sveltejs/kit/${'app_template_tag_missing'}`
	);
	error.name = 'SvelteKit error';
	throw error;
}
