/* This file is generated by scripts/process-messages/index.js. Do not edit! */

/** @import { ThrowOptions } from './internal/build.js' */
import { throw_error } from './internal/build.js';

/**
 * %file% does not exist
 * @param {{ "file": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function app_template_missing(_values, options) {
	throw_error('app_template_missing', `${_values.file} does not exist`, options, app_template_missing);
}

/**
 * %file% is missing `%tag%`
 * @param {{ "file": string; "tag": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function app_template_tag_missing(_values, options) {
	throw_error('app_template_tag_missing', `${_values.file} is missing \`${_values.tag}\``, options, app_template_tag_missing);
}

/**
 * Invalid alias key: `%key%`
 * @param {{ "key": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_alias_key_invalid(_values, options) {
	throw_error('config_alias_key_invalid', `Invalid alias key: \`${_values.key}\``, options, config_alias_key_invalid);
}

/**
 * Invalid alias value: `%value%`
 * @param {{ "value": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_alias_value_invalid(_values, options) {
	throw_error('config_alias_value_invalid', `Invalid alias value: \`${_values.value}\``, options, config_alias_value_invalid);
}

/**
 * `%keypath%` cannot start or end with `'/'`
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_app_dir_slash(_values, options) {
	throw_error('config_app_dir_slash', `\`${_values.keypath}\` cannot start or end with \`'/'\``, options, config_app_dir_slash);
}

/**
 * The `csp.directives['trusted-types']` option must include `'sveltekit-trusted-url'` when `serviceWorker.register` is `true`
 * @param {void} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_csp_trusted_types_missing(_values, options) {
	throw_error('config_csp_trusted_types_missing', `The \`csp.directives['trusted-types']\` option must include \`'sveltekit-trusted-url'\` when \`serviceWorker.register\` is \`true\``, options, config_csp_trusted_types_missing);
}

/**
 * `%keypath%` cannot be empty
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_empty_string(_values, options) {
	throw_error('config_empty_string', `\`${_values.keypath}\` cannot be empty`, options, config_empty_string);
}

/**
 * `%keypath%` should be true or false, if specified
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_expected_boolean(_values, options) {
	throw_error('config_expected_boolean', `\`${_values.keypath}\` should be true or false, if specified`, options, config_expected_boolean);
}

/**
 * `%keypath%` should be a function, if specified
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_expected_function(_values, options) {
	throw_error('config_expected_function', `\`${_values.keypath}\` should be a function, if specified`, options, config_expected_function);
}

/**
 * `%keypath%` should be a number, if specified
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_expected_number(_values, options) {
	throw_error('config_expected_number', `\`${_values.keypath}\` should be a number, if specified`, options, config_expected_number);
}

/**
 * `%keypath%` should be an object
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_expected_object(_values, options) {
	throw_error('config_expected_object', `\`${_values.keypath}\` should be an object`, options, config_expected_object);
}

/**
 * `%keypath%` should be %options%
 * @param {{ "keypath": string; "options": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_expected_one_of(_values, options) {
	throw_error('config_expected_one_of', `\`${_values.keypath}\` should be ${_values.options}`, options, config_expected_one_of);
}

/**
 * `%keypath%` should be a positive integer, if specified
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_expected_positive_integer(_values, options) {
	throw_error('config_expected_positive_integer', `\`${_values.keypath}\` should be a positive integer, if specified`, options, config_expected_positive_integer);
}

/**
 * `%keypath%` should be a string, if specified
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_expected_string(_values, options) {
	throw_error('config_expected_string', `\`${_values.keypath}\` should be a string, if specified`, options, config_expected_string);
}

/**
 * `%keypath%` should be an array of strings, if specified
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_expected_string_array(_values, options) {
	throw_error('config_expected_string_array', `\`${_values.keypath}\` should be an array of strings, if specified`, options, config_expected_string_array);
}

/**
 * File extensions must be alphanumeric — saw `'%extension%'`
 * @param {{ "extension": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_extension_invalid(_values, options) {
	throw_error('config_extension_invalid', `File extensions must be alphanumeric — saw \`'${_values.extension}'\``, options, config_extension_invalid);
}

/**
 * Each member of %keypath% must start with `'.'` — saw `'%extension%'`
 * @param {{ "keypath": string; "extension": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_extension_missing_dot(_values, options) {
	throw_error('config_extension_missing_dot', `Each member of ${_values.keypath} must start with \`'.'\` — saw \`'${_values.extension}'\``, options, config_extension_missing_dot);
}

/**
 * The SvelteKit Vite plugin `%keypath%` should be an object with an `adapt` method
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_invalid_adapter(_values, options) {
	throw_error('config_invalid_adapter', `The SvelteKit Vite plugin \`${_values.keypath}\` should be an object with an \`adapt\` method`, options, config_invalid_adapter);
}

/**
 * `%keypath%` should be `'fail'`, `'warn'`, `'ignore'` or a custom function
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_invalid_prerender_handler(_values, options) {
	throw_error('config_invalid_prerender_handler', `\`${_values.keypath}\` should be \`'fail'\`, \`'warn'\`, \`'ignore'\` or a custom function`, options, config_invalid_prerender_handler);
}

/**
 * SvelteKit configuration (%keys%) no longer lives inside a `kit` namespace. Pass it directly to the `sveltekit(...)` Vite plugin
 * @param {{ "keys": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_kit_namespace(_values, options) {
	throw_error('config_kit_namespace', `SvelteKit configuration (${_values.keys}) no longer lives inside a \`kit\` namespace. Pass it directly to the \`sveltekit(...)\` Vite plugin`, options, config_kit_namespace);
}

/**
 * The SvelteKit options from the Vite config must be an object
 * @param {void} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_not_object(_values, options) {
	throw_error('config_not_object', `The SvelteKit options from the Vite config must be an object`, options, config_not_object);
}

/**
 * The `%keypath%` option has been removed. Please see the list of breaking changes for your major release
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_option_removed(_values, options) {
	throw_error('config_option_removed', `The \`${_values.keypath}\` option has been removed. Please see the list of breaking changes for your major release`, options, config_option_removed);
}

/**
 * `%keypath%` has been removed in favour of `csrf.trustedOrigins`
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_option_removed_check_origin(_values, options) {
	throw_error('config_option_removed_check_origin', `\`${_values.keypath}\` has been removed in favour of \`csrf.trustedOrigins\``, options, config_option_removed_check_origin);
}

/**
 * `%keypath%` has been removed. `src/instrumentation.server.js` is now included in the build automatically when it exists; no opt-in is required
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_option_removed_experimental_instrumentation(_values, options) {
	throw_error('config_option_removed_experimental_instrumentation', `\`${_values.keypath}\` has been removed. \`src/instrumentation.server.js\` is now included in the build automatically when it exists; no opt-in is required`, options, config_option_removed_experimental_instrumentation);
}

/**
 * `%keypath%` has been removed. Server-side tracing is now configured via `tracing.server`
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_option_removed_experimental_tracing(_values, options) {
	throw_error('config_option_removed_experimental_tracing', `\`${_values.keypath}\` has been removed. Server-side tracing is now configured via \`tracing.server\``, options, config_option_removed_experimental_tracing);
}

/**
 * `%keypath%` has been removed. Use `#lib` instead of `$lib`: https://svelte.dev/docs/kit/$lib
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_option_removed_files_lib(_values, options) {
	throw_error('config_option_removed_files_lib', `\`${_values.keypath}\` has been removed. Use \`#lib\` instead of \`$lib\`: https://svelte.dev/docs/kit/$lib`, options, config_option_removed_files_lib);
}

/**
 * `%keypath%` has been removed. `modulepreload` will always be used
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_option_removed_preload_strategy(_values, options) {
	throw_error('config_option_removed_preload_strategy', `\`${_values.keypath}\` has been removed. \`modulepreload\` will always be used`, options, config_option_removed_preload_strategy);
}

/**
 * `%keypath%` has been removed in favour of `config.paths.origin`
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_option_removed_prerender_origin(_values, options) {
	throw_error('config_option_removed_prerender_origin', `\`${_values.keypath}\` has been removed in favour of \`config.paths.origin\``, options, config_option_removed_prerender_origin);
}

/**
 * `%keypath%` has been removed. Pass `vite-plugin-svelte` options directly to the `sveltekit(...)` Vite plugin
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_option_removed_vite_plugin(_values, options) {
	throw_error('config_option_removed_vite_plugin', `\`${_values.keypath}\` has been removed. Pass \`vite-plugin-svelte\` options directly to the \`sveltekit(...)\` Vite plugin`, options, config_option_removed_vite_plugin);
}

/**
 * `%keypath%` must be a valid origin — received `'%input%'` which contains a path, query, or hash. Use the bare origin `'%origin%'` instead
 * @param {{ "keypath": string; "input": string; "origin": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_origin_has_path(_values, options) {
	throw_error('config_origin_has_path', `\`${_values.keypath}\` must be a valid origin — received \`'${_values.input}'\` which contains a path, query, or hash. Use the bare origin \`'${_values.origin}'\` instead`, options, config_origin_has_path);
}

/**
 * `%keypath%` must be a valid origin (e.g. 'https://my-site.com'). `'%input%'` could not be parsed as a URL
 * @param {{ "keypath": string; "input": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_origin_invalid(_values, options) {
	throw_error('config_origin_invalid', `\`${_values.keypath}\` must be a valid origin (e.g. 'https://my-site.com'). \`'${_values.input}'\` could not be parsed as a URL`, options, config_origin_invalid);
}

/**
 * `%keypath%` must be a valid origin — only 'http' and 'https' protocols are supported, received '%protocol%'
 * @param {{ "keypath": string; "protocol": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_origin_protocol(_values, options) {
	throw_error('config_origin_protocol', `\`${_values.keypath}\` must be a valid origin — only 'http' and 'https' protocols are supported, received '${_values.protocol}'`, options, config_origin_protocol);
}

/**
 * `%keypath%` option must be an absolute path, if specified
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_paths_assets_not_absolute(_values, options) {
	throw_error('config_paths_assets_not_absolute', `\`${_values.keypath}\` option must be an absolute path, if specified`, options, config_paths_assets_not_absolute);
}

/**
 * `%keypath%` option must not end with `'/'`
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_paths_assets_trailing_slash(_values, options) {
	throw_error('config_paths_assets_trailing_slash', `\`${_values.keypath}\` option must not end with \`'/'\``, options, config_paths_assets_trailing_slash);
}

/**
 * `%keypath%` option must either be the empty string or a root-relative path that starts but doesn't end with `'/'`
 * @param {{ "keypath": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_paths_base_invalid(_values, options) {
	throw_error('config_paths_base_invalid', `\`${_values.keypath}\` option must either be the empty string or a root-relative path that starts but doesn't end with \`'/'\``, options, config_paths_base_invalid);
}

/**
 * Each member of `%keypath%` must be either `'*'` or an absolute path beginning with `'/'` — saw `'%entry%'`
 * @param {{ "keypath": string; "entry": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_prerender_entry_invalid(_values, options) {
	throw_error('config_prerender_entry_invalid', `Each member of \`${_values.keypath}\` must be either \`'*'\` or an absolute path beginning with \`'/'\` — saw \`'${_values.entry}'\``, options, config_prerender_entry_invalid);
}

/**
 * The `router.resolution` option cannot be `'server'` if `output.bundleStrategy` is `'inline'` or `'single'`
 * @param {void} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_server_resolution_bundle_strategy(_values, options) {
	throw_error('config_server_resolution_bundle_strategy', `The \`router.resolution\` option cannot be \`'server'\` if \`output.bundleStrategy\` is \`'inline'\` or \`'single'\``, options, config_server_resolution_bundle_strategy);
}

/**
 * The `router.resolution` option cannot be `'server'` if `router.type` is `'hash'`
 * @param {void} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_server_resolution_hash(_values, options) {
	throw_error('config_server_resolution_hash', `The \`router.resolution\` option cannot be \`'server'\` if \`router.type\` is \`'hash'\``, options, config_server_resolution_hash);
}

/**
 * Unexpected option `%keypath%`
 * @param {{ "keypath": string; "suggestion"?: string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function config_unexpected_option(_values, options) {
	throw_error('config_unexpected_option', (_values?.suggestion !== undefined ? `Unexpected option \`${_values.keypath}\` (did you mean \`${_values.suggestion}\`?)` : `Unexpected option \`${_values.keypath}\``), options, config_unexpected_option);
}

/**
 * Cannot import `$app/*` modules other than `$app/env` inside `src/env`
 * @param {void} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function env_app_import(_values, options) {
	throw_error('env_app_import', `Cannot import \`$app/*\` modules other than \`$app/env\` inside \`src/env\``, options, env_app_import);
}

/**
 * Cannot import `$app/env/%type%` inside `src/env` or its dependencies because it creates a circular dependency
 * @param {{ "type": string; "importer"?: string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function env_circular_import(_values, options) {
	throw_error('env_circular_import', (_values?.importer !== undefined ? `Module \`${_values.importer}\` imports \`$app/env/${_values.type}\`, which creates a circular dependency with \`src/env\`` : `Cannot import \`$app/env/${_values.type}\` inside \`src/env\` or its dependencies because it creates a circular dependency`), options, env_circular_import);
}

/**
 * Invalid environment variable name `%name%`
 * @param {{ "name": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function env_invalid_variable_name(_values, options) {
	throw_error('env_invalid_variable_name', `Invalid environment variable name \`${_values.name}\``, options, env_invalid_variable_name);
}

/**
 * `%file%` must export a variables object
 * @param {{ "file": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function env_variables_missing(_values, options) {
	throw_error('env_variables_missing', `\`${_values.file}\` must export a variables object`, options, env_variables_missing);
}

/**
 * No matcher found for parameter `%name%`
 * @param {{ "name": string; "file"?: string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function param_matcher_missing(_values, options) {
	throw_error('param_matcher_missing', (_values?.file !== undefined ? `No matcher found for parameter \`${_values.name}\` in \`${_values.file}\`` : `No matcher found for parameter \`${_values.name}\``), options, param_matcher_missing);
}

/**
 * `%file%` does not export `params` from `defineParams`
 * @param {{ "file": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function params_export_missing(_values, options) {
	throw_error('params_export_missing', `\`${_values.file}\` does not export \`params\` from \`defineParams\``, options, params_export_missing);
}

/**
 * The `%first%` and `%second%` routes conflict with each other
 * @param {{ "first": string; "second": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_conflict(_values, options) {
	throw_error('route_conflict', `The \`${_values.first}\` and \`${_values.second}\` routes conflict with each other`, options, route_conflict);
}

/**
 * Multiple %type% files found in `%directory%` : `%existing%` and `%file%`
 * @param {{ "type": string; "directory": string; "existing": string; "file": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_duplicate_files(_values, options) {
	throw_error('route_duplicate_files', `Multiple ${_values.type} files found in \`${_values.directory}\` : \`${_values.existing}\` and \`${_values.file}\``, options, route_duplicate_files);
}

/**
 * Hexadecimal escape sequence in `%id%` must be two characters
 * @param {{ "id": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_escape_hex_length(_values, options) {
	throw_error('route_escape_hex_length', `Hexadecimal escape sequence in \`${_values.id}\` must be two characters`, options, route_escape_hex_length);
}

/**
 * Invalid character escape sequence in `%id%`
 * @param {{ "id": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_escape_invalid(_values, options) {
	throw_error('route_escape_invalid', `Invalid character escape sequence in \`${_values.id}\``, options, route_escape_invalid);
}

/**
 * Unicode escape sequence in `%id%` must be between four and six characters
 * @param {{ "id": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_escape_unicode_length(_values, options) {
	throw_error('route_escape_unicode_length', `Unicode escape sequence in \`${_values.id}\` must be between four and six characters`, options, route_escape_unicode_length);
}

/**
 * Character escape sequence in `%id%` must be lowercase
 * @param {{ "id": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_escape_uppercase(_values, options) {
	throw_error('route_escape_uppercase', `Character escape sequence in \`${_values.id}\` must be lowercase`, options, route_escape_uppercase);
}

/**
 * Files prefixed with `+` are reserved (saw `%file%`)
 * @param {{ "file": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_file_reserved(_values, options) {
	throw_error('route_file_reserved', `Files prefixed with \`+\` are reserved (saw \`${_values.file}\`)`, options, route_file_reserved);
}

/**
 * Route `%id%` should be renamed to %suggestion%
 * @param {{ "id": string; "suggestion": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_hash_character(_values, options) {
	throw_error('route_hash_character', `Route \`${_values.id}\` should be renamed to ${_values.suggestion}`, options, route_hash_character);
}

/**
 * `%file%` references missing segment `%segment%`
 * @param {{ "file": string; "segment": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_layout_segment_missing(_values, options) {
	throw_error('route_layout_segment_missing', `\`${_values.file}\` references missing segment \`${_values.segment}\``, options, route_layout_segment_missing);
}

/**
 * Only Svelte files can reference named layouts. Remove `%layout%` from `%name%` (at `%file%`)
 * @param {{ "layout": string; "name": string; "file": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_named_layout_in_module(_values, options) {
	throw_error('route_named_layout_in_module', `Only Svelte files can reference named layouts. Remove \`${_values.layout}\` from \`${_values.name}\` (at \`${_values.file}\`)`, options, route_named_layout_in_module);
}

/**
 * Invalid route `%id%` — an `[[optional]]` route segment cannot follow a `[...rest]` route segment
 * @param {{ "id": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_optional_after_rest(_values, options) {
	throw_error('route_optional_after_rest', `Invalid route \`${_values.id}\` — an \`[[optional]]\` route segment cannot follow a \`[...rest]\` route segment`, options, route_optional_after_rest);
}

/**
 * Invalid route `%id%` — a rest route segment is always optional, remove the outer square brackets
 * @param {{ "id": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_optional_rest(_values, options) {
	throw_error('route_optional_rest', `Invalid route \`${_values.id}\` — a rest route segment is always optional, remove the outer square brackets`, options, route_optional_rest);
}

/**
 * Invalid param: %param% in route `%id%`. Params and matcher names can only have underscores, hyphens, and alphanumeric characters.
 * @param {{ "param": string; "id": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_param_invalid(_values, options) {
	throw_error('route_param_invalid', `Invalid param: ${_values.param} in route \`${_values.id}\`. Params and matcher names can only have underscores, hyphens, and alphanumeric characters.`, options, route_param_invalid);
}

/**
 * Invalid route `%id%` — parameters must be separated
 * @param {{ "id": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_params_adjacent(_values, options) {
	throw_error('route_params_adjacent', `Invalid route \`${_values.id}\` — parameters must be separated`, options, route_params_adjacent);
}

/**
 * Cannot prerender a route (`%id%`) with both a `+page.svelte` and a `%file%`
 * @param {{ "id": string; "file": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_prerender_page_and_endpoint(_values, options) {
	throw_error('route_prerender_page_and_endpoint', `Cannot prerender a route (\`${_values.id}\`) with both a \`+page.svelte\` and a \`${_values.file}\``, options, route_prerender_page_and_endpoint);
}

/**
 * Cannot use server-only files in an app with `router.type === 'hash'`: `%file%`
 * @param {{ "file": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_server_file_hash_router(_values, options) {
	throw_error('route_server_file_hash_router', `Cannot use server-only files in an app with \`router.type === 'hash'\`: \`${_values.file}\``, options, route_server_file_hash_router);
}

/**
 * Invalid route `%id%` — brackets are unbalanced
 * @param {{ "id": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function route_unbalanced_brackets(_values, options) {
	throw_error('route_unbalanced_brackets', `Invalid route \`${_values.id}\` — brackets are unbalanced`, options, route_unbalanced_brackets);
}

/**
 * No routes found. If you are using a custom `src/routes` directory, make sure it is specified in your SvelteKit Vite plugin options
 * @param {void} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function routes_not_found(_values, options) {
	throw_error('routes_not_found', `No routes found. If you are using a custom \`src/routes\` directory, make sure it is specified in your SvelteKit Vite plugin options`, options, routes_not_found);
}

/**
 * Failed to parse TypeScript config
 * @param {void | { "details": string }} _values
 * @param {ThrowOptions} [options]
 * @returns {never}
 */
export function tsconfig_parse_failed(_values, options) {
	throw_error('tsconfig_parse_failed', (_values?.details !== undefined ? `Failed to parse TypeScript config: ${_values.details}` : `Failed to parse TypeScript config`), options, tsconfig_parse_failed);
}
