/* This file is generated by scripts/process-messages/index.js. Do not edit! */

/** @import { ServerThrowOptions } from './internal/server.js' */
import { throw_error } from './internal/server.js';

/**
 * `defineEnvVars` has moved — import it from `@sveltejs/kit/env` instead
 * @param {void} _values
 * @param {ServerThrowOptions} [options]
 * @returns {never}
 */
export function define_env_vars_moved(_values, options) {
	throw_error('define_env_vars_moved', `\`defineEnvVars\` has moved — import it from \`@sveltejs/kit/env\` instead`, options, define_env_vars_moved);
}

/**
 * Invalid environment variables:
%issues%
 * @param {{ "issues": string }} _values
 * @param {ServerThrowOptions} [options]
 * @returns {never}
 */
export function env_invalid(_values, options) {
	throw_error('env_invalid', `Invalid environment variables:
${_values.issues}`, options, env_invalid);
}

/**
 * Asset does not exist: %file%
 * @param {{ "file": string }} _values
 * @param {ServerThrowOptions} [options]
 * @returns {never}
 */
export function read_asset_missing(_values, options) {
	throw_error('read_asset_missing', `Asset does not exist: ${_values.file}`, options, read_asset_missing);
}

/**
 * No `read` implementation was provided. Please ensure that your adapter is up to date and supports this feature
 * @param {void} _values
 * @param {ServerThrowOptions} [options]
 * @returns {never}
 */
export function read_implementation_missing(_values, options) {
	throw_error('read_implementation_missing', `No \`read\` implementation was provided. Please ensure that your adapter is up to date and supports this feature`, options, read_implementation_missing);
}

/**
 * Cannot call `%name%` on the server
 * @param {{ "name": string }} _values
 * @param {ServerThrowOptions} [options]
 * @returns {never}
 */
export function server_api_unavailable(_values, options) {
	throw_error('server_api_unavailable', `Cannot call \`${_values.name}\` on the server`, options, server_api_unavailable);
}

/**
 * Can only read '%name%' on the server during rendering (not in e.g. `load` functions), as it is bound to the current request via component context. This prevents state from leaking between users.
 * @param {{ "name": string }} _values
 * @param {ServerThrowOptions} [options]
 * @returns {never}
 */
export function state_read_outside_render(_values, options) {
	throw_error('state_read_outside_render', `Can only read '${_values.name}' on the server during rendering (not in e.g. \`load\` functions), as it is bound to the current request via component context. This prevents state from leaking between users.`, options, state_read_outside_render);
}

/**
 * Cannot access url.%property% on a page with prerendering enabled
 * @param {{ "property": string }} _values
 * @param {ServerThrowOptions} [options]
 * @returns {never}
 */
export function url_search_unavailable_prerender(_values, options) {
	throw_error('url_search_unavailable_prerender', `Cannot access url.${_values.property} on a page with prerendering enabled`, options, url_search_unavailable_prerender);
}
