/* This file is generated by scripts/process-messages/index.js. Do not edit! */

import { BROWSER, DEV } from 'esm-env';
import { throw_error, verbose } from './internal/shared.js';

/**
 * Invalid export `%key%` (valid exports are %exports%, or anything with a `'_'` prefix)
 * @param {{ "key": string; "exports": string; "file"?: string }} _values
 * @returns {never}
 */
export function invalid_export(_values) {
	if (DEV || (!BROWSER && verbose)) {
		throw_error('invalid_export', (_values?.file !== undefined ? `Invalid export \`${_values.key}\` in \`${_values.file}\` (valid exports are ${_values.exports}, or anything with a \`'_'\` prefix)` : `Invalid export \`${_values.key}\` (valid exports are ${_values.exports}, or anything with a \`'_'\` prefix)`), invalid_export);
	}

	throw new Error('https://next.svelte.dev/e/@sveltejs/kit/invalid_export');
}

/**
 * Invalid export `%key%` (`%key%` is a valid export in %locations%)
 * @param {{ "key": string; "locations": string; "file"?: string }} _values
 * @returns {never}
 */
export function invalid_export_location(_values) {
	if (DEV || (!BROWSER && verbose)) {
		throw_error('invalid_export_location', (_values?.file !== undefined ? `Invalid export \`${_values.key}\` in \`${_values.file}\` (\`${_values.key}\` is a valid export in ${_values.locations})` : `Invalid export \`${_values.key}\` (\`${_values.key}\` is a valid export in ${_values.locations})`), invalid_export_location);
	}

	throw new Error('https://next.svelte.dev/e/@sveltejs/kit/invalid_export_location');
}

/**
 * Invalid param definition
 * @param {void} _values
 * @returns {never}
 */
export function param_definition_invalid(_values) {
	if (DEV || (!BROWSER && verbose)) {
		throw_error('param_definition_invalid', `Invalid param definition`, param_definition_invalid);
	}

	throw new Error('https://next.svelte.dev/e/@sveltejs/kit/param_definition_invalid');
}

/**
 * Async param matchers are not supported
 * @param {void} _values
 * @returns {never}
 */
export function param_matcher_async(_values) {
	if (DEV || (!BROWSER && verbose)) {
		throw_error('param_matcher_async', `Async param matchers are not supported`, param_matcher_async);
	}

	throw new Error('https://next.svelte.dev/e/@sveltejs/kit/param_matcher_async');
}

/**
 * Param matcher must return a string, number, boolean, or bigint
 * @param {void} _values
 * @returns {never}
 */
export function param_matcher_result_invalid(_values) {
	if (DEV || (!BROWSER && verbose)) {
		throw_error('param_matcher_result_invalid', `Param matcher must return a string, number, boolean, or bigint`, param_matcher_result_invalid);
	}

	throw new Error('https://next.svelte.dev/e/@sveltejs/kit/param_matcher_result_invalid');
}

/**
 * Missing parameter `%name%` in route `%id%`
 * @param {{ "name": string; "id": string }} _values
 * @returns {never}
 */
export function route_param_missing(_values) {
	if (DEV || (!BROWSER && verbose)) {
		throw_error('route_param_missing', `Missing parameter \`${_values.name}\` in route \`${_values.id}\``, route_param_missing);
	}

	throw new Error('https://next.svelte.dev/e/@sveltejs/kit/route_param_missing');
}

/**
 * Parameter `%name%` in route `%id%` cannot start or end with a slash — this would cause an invalid route like `foo/bar`
 * @param {{ "name": string; "id": string }} _values
 * @returns {never}
 */
export function route_param_slash(_values) {
	if (DEV || (!BROWSER && verbose)) {
		throw_error('route_param_slash', `Parameter \`${_values.name}\` in route \`${_values.id}\` cannot start or end with a slash — this would cause an invalid route like \`foo/bar\``, route_param_slash);
	}

	throw new Error('https://next.svelte.dev/e/@sveltejs/kit/route_param_slash');
}

/**
 * Parameter `%name%` in route `%id%` must be a string, number, boolean, or bigint
 * @param {{ "name": string; "id": string }} _values
 * @returns {never}
 */
export function route_param_value_invalid(_values) {
	if (DEV || (!BROWSER && verbose)) {
		throw_error('route_param_value_invalid', `Parameter \`${_values.name}\` in route \`${_values.id}\` must be a string, number, boolean, or bigint`, route_param_value_invalid);
	}

	throw new Error('https://next.svelte.dev/e/@sveltejs/kit/route_param_value_invalid');
}
