packages:
  - packages/*
  - packages/adapter-cloudflare/test/apps/*
  - packages/adapter-netlify/test/apps/*
  - packages/adapter-static/test/apps/*
  - packages/kit/test/apps/*
  - packages/kit/test/prerendering/*
  - packages/kit/test/build-errors/**
  - packages/kit/test/build-errors/apps/*
  - '!.test-tmp/**'
  - playgrounds/*
catalog:
  '@changesets/cli': ^2.29.6
  '@fontsource/libre-barcode-128-text': ^5.1.0
  '@netlify/edge-functions': ^2.15.1
  '@netlify/functions': ^4.0.0
  '@opentelemetry/sdk-node': ^0.205.0
  '@opentelemetry/sdk-trace-node': ^2.0.1
  '@playwright/test': ^1.51.1
  '@polka/url': ^1.0.0-next.28
  '@rollup/plugin-commonjs': ^28.0.1
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^16.0.0
  '@sveltejs/eslint-config': ^8.2.0
  '@sveltejs/vite-plugin-svelte': ^6.0.0-next.3
  '@svitejs/changesets-changelog-github-compact': ^1.2.0
  '@types/connect': ^3.4.38
  '@types/estree': ^1.0.5
  '@types/node': ^18.19.119
  '@types/semver': ^7.5.6
  '@types/set-cookie-parser': ^2.4.7
  '@vercel/nft': ^0.30.0
  '@vitest/browser': ^3.2.4
  dropcss: ^1.0.16
  dts-buddy: ^0.6.2
  esbuild: ^0.25.4
  eslint: ^9.34.0
  netlify-cli: ^23.5.1
  polka: ^1.0.0-next.28
  publint: ^0.3.0
  semver: ^7.5.4
  sirv-cli: ^3.0.0
  svelte: ^5.39.3
  svelte-check: ^4.1.1
  svelte-preprocess: ^6.0.0
  typescript-eslint: ^8.43.0
  valibot: ^1.1.0
  vite: ^6.3.5
  vitest: ^3.2.4
  wrangler: ^4.14.3
