packages:
  - 'packages/*'
  - 'packages/adapter-static/test/apps/*'
  - 'packages/kit/test/apps/*'
  - 'packages/kit/test/prerendering/*'
  - 'packages/kit/test/build-errors/**'
  - 'packages/kit/test/build-errors/apps/*'
  - 'packages/create-svelte/templates/*'
  - '!.test-tmp/**'
  - 'playgrounds/*'
