packages:
  - 'packages/*'
  - 'packages/adapter-cloudflare/test/apps/*'
  - 'packages/adapter-static/test/apps/*'
  - 'packages/kit/test/apps/*'
  - 'packages/kit/test/prerendering/*'
  - 'packages/kit/test/build-errors/**'
  - 'packages/kit/test/build-errors/apps/*'
  - 'packages/create-svelte/templates/*'
  - '!.test-tmp/**'
  - 'playgrounds/*'

catalog:
  "playwright": "^1.51.1"
  "@playwright/test": "^1.51.1"
