packages:
  - 'packages/*'
  - 'packages/adapter-cloudflare/test/apps/*'
  - 'packages/adapter-netlify/test/apps/*'
  - 'packages/adapter-static/test/apps/*'
  - 'packages/kit/test/apps/*'
  - 'packages/kit/test/prerendering/*'
  - 'packages/kit/test/build-errors/**'
  - 'packages/kit/test/build-errors/apps/*'
  - 'packages/create-svelte/templates/*'
  - '!.test-tmp/**'
  - 'playgrounds/*'

catalog:
  '@playwright/test': '^1.51.1'
  '@sveltejs/vite-plugin-svelte': '^6.1.0'
  '@types/node': '^20.14.8'
  'cross-env': '^7.0.3'
  'vitest': '^3.2.3'
  'vite': '^7.0.3'
