packages:
  - packages/*
  - packages/adapter-cloudflare/test/apps/*
  - packages/adapter-netlify/test/apps/*
  - packages/adapter-static/test/apps/*
  - packages/kit/test/apps/*
  - packages/kit/test/prerendering/*
  - packages/kit/test/build-errors/**
  - packages/kit/test/build-errors/apps/*
  - "!.test-tmp/**"
  - playgrounds/*
catalog:
  "@changesets/cli": ^2.29.6
  "@cloudflare/workers-types": ^4.20250507.0
  "@fontsource/libre-barcode-128-text": ^5.1.0
  "@iarna/toml": ^2.2.5
  "@netlify/edge-functions": ^2.15.1
  "@netlify/functions": ^4.0.0
  "@opentelemetry/sdk-node": ^0.205.0
  "@opentelemetry/sdk-trace-node": ^2.0.1
  "@playwright/test": ^1.51.1
  "@polka/url": ^1.0.0-next.28
  "@rollup/plugin-commonjs": ^28.0.1
  "@rollup/plugin-json": ^6.1.0
  "@rollup/plugin-node-resolve": ^16.0.0
  "@standard-schema/spec": ^1.0.0
  "@sveltejs/acorn-typescript": ^1.0.5
  "@sveltejs/eslint-config": ^8.2.0
  "@sveltejs/vite-plugin-svelte": ^6.0.0-next.3
  "@svitejs/changesets-changelog-github-compact": ^1.2.0
  "@types/connect": ^3.4.38
  "@types/cookie": ^0.6.0
  "@types/estree": ^1.0.5
  "@types/node": ^18.19.119
  "@types/semver": ^7.5.6
  "@types/set-cookie-parser": ^2.4.7
  "@vercel/nft": ^0.30.0
  "@vitest/browser": ^3.2.4
  acorn: ^8.14.1
  chokidar: ^4.0.3
  cookie: ^0.6.0
  devalue: ^5.3.2
  dropcss: ^1.0.16
  dts-buddy: ^0.6.2
  esbuild: ^0.25.4
  eslint: ^9.34.0
  esm-env: ^1.2.2
  kleur: ^4.1.5
  magic-string: ^0.30.5
  mrmime: ^2.0.0
  netlify-cli: ^23.5.1
  polka: ^1.0.0-next.28
  publint: ^0.3.0
  sade: ^1.8.1
  semver: ^7.5.4
  set-cookie-parser: ^2.6.0
  sharp: ^0.34.4
  sirv-cli: ^3.0.0
  svelte: ^5.39.3
  svelte-check: ^4.1.1
  svelte-parse-markup: ^0.1.5
  svelte-preprocess: ^6.0.0
  svelte2tsx: ~0.7.33
  typescript-eslint: ^8.43.0
  valibot: ^1.1.0
  vite: ^6.3.5
  vite-imagetools: ^8.0.0
  vitest: ^3.2.4
  worktop: 0.8.0-next.18
  wrangler: ^4.14.3
  zimmerframe: ^1.1.2
