verifyDepsBeforeRun: warn
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@sveltejs/*'
  - svelte
  - esrap
  - devalue
  - dts-buddy
  - zimmerframe
  - prettier-plugin-svelte
  - svelte-check
  - svelte2tsx
  - esm-env
  - vite-imagetools
  - imagetools-core
  # TODO: remove these when they're older than 2 days
  - miniflare@5.20260804.0-alpha
  - wrangler@4.120.1
  - '@changesets/apply-release-plan@8.0.0'
  - '@changesets/assemble-release-plan@7.0.0'
  - '@changesets/changelog-git@1.0.0'
  - '@changesets/cli@3.0.0'
  - '@changesets/config@4.0.0'
  - '@changesets/errors@1.0.0'
  - '@changesets/get-dependents-graph@3.0.0'
  - '@changesets/git@4.0.0'
  - '@changesets/parse@1.0.0'
  - '@changesets/pre@3.0.0'
  - '@changesets/read@1.0.0'
  - '@changesets/should-skip-package@1.0.0'
  - '@changesets/types@7.0.0'
  - '@changesets/write@1.0.0'
blockExoticSubdeps: true
linkWorkspacePackages: true
shellEmulator: true
engineStrict: true

packages:
  - packages/*
  - packages/adapter-cloudflare/test/apps/*
  - packages/adapter-netlify/test/apps/*
  - packages/adapter-node/test/apps/*
  - packages/adapter-vercel/test/apps/*
  - packages/adapter-static/test/apps/*
  - packages/enhanced-img/test/apps/*
  - packages/kit/src/core/sync/write_types/test/*
  - packages/kit/test/apps/*
  - packages/kit/test/prerendering/*
  - packages/kit/test/build-errors/**
  - packages/kit/test/build-errors/apps/*
  - '!.test-tmp/**'
  - playgrounds/*
allowBuilds:
  esbuild: true
  protobufjs: false # postinstall script only prints warnings
  rolldown: true
  sharp: true
  svelte-preprocess: false # postinstall script only prints warnings
  workerd: true
# pnpm catalogs are currently only suitable for dependencies that
# wouldn't require publishing a new package version
# see https://github.com/changesets/changesets/issues/1707
catalog:
  '@changesets/cli': ^3.0.0
  # pin the version of changelog-github because we're using the experimental
  # template feature which can change in a patch version
  '@changesets/changelog-github': 1.0.0-next.9
  '@fontsource/libre-barcode-128-text': ^5.3.0
  '@opentelemetry/api': ^1.9.1
  '@opentelemetry/sdk-node': ^0.221.0
  '@opentelemetry/sdk-trace-node': ^2.8.0
  '@playwright/test': ^1.62.0
  '@polka/url': ^1.0.0-next.29
  '@standard-schema/spec': ^1.1.0
  '@sveltejs/eslint-config': ^10.0.4
  '@sveltejs/vite-plugin-svelte': ^7.3.0
  '@types/connect': ^3.4.38
  '@types/estree': ^1.0.8
  '@types/node': ^22.19.19
  '@types/semver': ^7.8.0
  eslint: ^10.8.1
  polka: ^1.0.0-next.28
  prettier: ^3.9.6
  prettier-plugin-svelte: ^4.1.1
  rolldown: ^1.2.3
  semver: ^7.5.4
  sirv-cli: ^3.0.1
  svelte: ^5.56.8
  svelte-check: ^4.7.5
  svelte-preprocess: ^6.0.5
  # This version of TypeScript is for apps using it just for type checking.
  # `kit` and `package` cannot follow the catalog version because they require it
  # for generating types and TypeScript can have breaking changes in minors
  typescript: ^6.0.3
  '@typescript/native': npm:typescript@^7.0.2
  valibot: ^1.4.2
  vite: ^8.2.1
  wrangler: ^4.120.1

  # unit test deps that should be upgraded together
  '@vitest/browser-playwright': ^4.1.10
  vitest: ^4.1.10
  jsdom: ^30.0.0
catalogs:
  typescript-native:
    typescript: ^7.0.2
  # these show up in the ci.yml like `vite: 'beta'`, etc.
  vite-baseline:
    vite: ^8.0.12
    '@sveltejs/vite-plugin-svelte': ^7.0.0
  # TODO: uncomment this when we start working on Vite 9 support
  # vite-beta:
  #   vite: ^9.0.0-beta.0
  #   '@sveltejs/vite-plugin-svelte': ^7.0.0
overrides: {}
  # ci script replaces all overrides with the vite-xxx or node-xx catalogs above.
  # if you want to introduce an override, make sure to add it to all of them too
