// generated by `adapt` in the output directory
declare module '#@sveltejs/adapter-node' {
	export const server: import('@sveltejs/kit').Server;
	/** the output directory */
	export const dir: string;
	export const base: string;
	export const app_path: string;
	export const origin: string | undefined;
	export const env_prefix: string;
	export const precompress: boolean;
	export const uncompressed_extensions: Set<string>;
	export const prerendered: Set<string>;
	export const mime_types: Record<string, string>;
}
