// generated by `adapt` in the output directory
declare module '#@sveltejs/adapter-node' {
	export const server: import('@sveltejs/kit').Server;
	/** the output directory */
	export const dir: string;
	export const base: string;
	export const app_path: string;
	export const origin: string | undefined;
	export const env_prefix: string;
	export const mime_types: Record<string, string>;
	export const assets: AssetTable;
	export const prerendered_assets: AssetTable;
}

interface AssetEntry {
	/** path on disk, relative to the served directory */
	file: string;
	size: number;
	/** content hash */
	etag: string;
	/** size and content hash of the gzip variant, if one was written */
	gz?: [number, string];
	/** size and content hash of the brotli variant, if one was written */
	br?: [number, string];
}

interface AssetTable {
	entries: Array<[string, AssetEntry]>;
	/** `[alias, key]` pairs, e.g. `['/about', '/about.html']` */
	aliases: Array<[string, string]>;
}
