/** @import { Unstable_Config } from 'wrangler' */
import { existsSync } from 'node:fs';
import process from 'node:process';

/**
 * @param {Unstable_Config} wrangler_config
 * @returns {boolean}
 */
export function is_building_for_cloudflare_pages(wrangler_config) {
	if (
		process.env.CF_PAGES ||
		wrangler_config.pages_build_output_dir ||
		existsSync('_routes.json')
	) {
		return true;
	}

	if (!!process.env.WORKERS_CI || wrangler_config.main || wrangler_config.assets) {
		return false;
	}

	return true;
}

/**
 * @param {Unstable_Config} wrangler_config
 */
export function validate_worker_settings(wrangler_config) {
	const config_path = wrangler_config.configPath || 'your wrangler.jsonc file';

	// we don't support workers sites
	if (wrangler_config.site) {
		throw new Error(
			`You must remove all \`site\` keys in ${config_path}. Consult https://svelte.dev/docs/kit/adapter-cloudflare#Migrating-from-Workers-Sites`
		);
	}

	if (wrangler_config.assets?.directory) {
		throw new Error(
			`You must remove the \`assets.directory\` key in ${config_path}. You can change the output directory by setting \`outDir\` in your SvelteKit config.`
		);
	}
	if (wrangler_config.main?.endsWith('.svelte-kit/cloudflare/_worker.js')) {
		throw new Error(
			`The \`main\` key in ${config_path} is now used to specify a custom Worker entrypoint. You must remove it unless you are using a custom Worker.`
		);
	}
}

/**
 * Adds header rules to the contents of a `_headers` file
 * @param {string} url
 * @param {string[]} rules
 * @param {string} content
 * @returns {string}
 */
export function append_headers(url, rules, content) {
	const regex = new RegExp(`^(${url.replaceAll('*', '\\*')})$`, 'm');
	const formatted_headers = rules.map((rule) => `  ${rule}`).join('\n');

	// if the URL already exists, just add header rules to it
	if (regex.test(content)) {
		return content.replace(regex, `$1\n${formatted_headers}`);
	}

	// otherwise, we add the url and header rules
	return `
${content}
# === START AUTOGENERATED SVELTE IMMUTABLE HEADERS ===
${url}
${formatted_headers}
# === END AUTOGENERATED SVELTE IMMUTABLE HEADERS ===
`.trim();
}
