/** @import { Unstable_Config } from 'wrangler' */
import { existsSync } from 'node:fs';
import process from 'node:process';

/**
 * @param {Unstable_Config} wrangler_config
 * @returns {boolean}
 */
export function is_building_for_cloudflare_pages(wrangler_config) {
	if (
		process.env.CF_PAGES ||
		wrangler_config.pages_build_output_dir ||
		existsSync('_routes.json')
	) {
		return true;
	}

	if (!!process.env.WORKERS_CI || wrangler_config.main || wrangler_config.assets) {
		return false;
	}

	return true;
}

/**
 * @param {Unstable_Config} wrangler_config
 */
export function validate_worker_settings(wrangler_config) {
	const config_path = wrangler_config.configPath || 'your wrangler.jsonc file';

	// we don't support workers sites
	if (wrangler_config.site) {
		throw new Error(
			`You must remove all \`site\` keys in ${config_path}. Consult https://svelte.dev/docs/kit/adapter-cloudflare#Migrating-from-Workers-Sites`
		);
	}

	// we need the `assets.directory` key so that the static assets are deployed
	if ((wrangler_config.main || wrangler_config.assets) && !wrangler_config.assets?.directory) {
		throw new Error(
			`You must specify the \`assets.directory\` key in ${config_path}. Consult https://developers.cloudflare.com/workers/static-assets/binding/#directory`
		);
	}

	// we need the `assets.binding` key so that the Worker can access the static assets
	if (wrangler_config.main && !wrangler_config.assets?.binding) {
		throw new Error(
			`You must specify the \`assets.binding\` key in ${config_path} before deploying your Worker. Consult https://developers.cloudflare.com/workers/static-assets/binding/#binding`
		);
	}

	// the user might have forgot the `main` key or should remove the `assets.binding`
	// key to deploy static assets without a Worker
	if (!wrangler_config.main && wrangler_config.assets?.binding) {
		throw new Error(
			`You must specify the \`main\` key in ${config_path} if you want to deploy a Worker alongside your static assets. Otherwise, remove the \`assets.binding\` key if you only want to deploy static assets.`
		);
	}
}

/**
 * Extracts the redirect source from each line of a [_redirects](https://developers.cloudflare.com/pages/configuration/redirects/)
 * file so we can exclude them in [_routes.json](https://developers.cloudflare.com/pages/functions/routing/#create-a-_routesjson-file)
 * to ensure the redirect is invoked instead of the Cloudflare Worker.
 * @param {string} file_contents
 * @returns {string[]}
 */
export function parse_redirects(file_contents) {
	/** @type {string[]} */
	const redirects = [];

	for (const line of file_contents.split('\n')) {
		const content = line.trim();
		if (!content || content.startsWith('#')) continue;

		const [pathname] = line.split(' ');
		// pathnames with placeholders are not supported
		if (!pathname || pathname.includes('/:')) {
			throw new Error(`The following _redirects rule cannot be excluded by _routes.json: ${line}`);
		}
		redirects.push(pathname);
	}

	return redirects;
}

/**
 * Adds header rules to the contents of a `_headers` file
 * @param {string} url
 * @param {string[]} rules
 * @param {string} content
 * @returns {string}
 */
export function append_headers(url, rules, content) {
	const regex = new RegExp(`^(${url.replaceAll('*', '\\*')})$`, 'm');
	const formatted_headers = rules.map((rule) => `  ${rule}`).join('\n');

	// if the URL already exists, just add header rules to it
	if (regex.test(content)) {
		return content.replace(regex, `$1\n${formatted_headers}`);
	}

	// otherwise, we add the url and header rules
	return `
${content}
# === START AUTOGENERATED SVELTE IMMUTABLE HEADERS ===
${url}
${formatted_headers}
# === END AUTOGENERATED SVELTE IMMUTABLE HEADERS ===
`.trim();
}
