import { dedent, write_if_changed } from './utils.js';

/**
 * @param {import('types').ManifestData} manifest_data
 * @param {string} output
 */
export function write_root(manifest_data, output) {
	// TODO remove default layout altogether

	const max_depth = Math.max(
		...manifest_data.routes.map((route) =>
			route.page ? route.page.layouts.filter(Boolean).length + 1 : 0
		),
		1
	);

	const levels = [];
	for (let i = 0; i <= max_depth; i += 1) {
		levels.push(i);
	}

	// with the @const we force the data[depth] access to be derived, which is important to not fire updates needlessly
	// TODO in Svelte 5 we should rethink the client.js side, we can likely make data a $state and only update indexes that changed there, simplifying this a lot
	const pyramid = dedent`
		{#snippet pyramid(depth)}
			{@const Pyramid = constructors[depth]}
			{#snippet failed(error)}
				{@const ErrorPage = errors[depth]}
				<ErrorPage {error} />
			{/snippet}
			<svelte:boundary failed={errors[depth] ? failed : undefined}>
				{#if constructors[depth + 1]}
					{@const d = data[depth]}
					<!-- svelte-ignore binding_property_non_reactive -->
					<Pyramid bind:this={components[depth]} data={d} {form} params={page.params}>
						{@render pyramid(depth + 1)}
					</Pyramid>
				{:else}
					{@const d = data[depth]}
					<!-- svelte-ignore binding_property_non_reactive -->
					<Pyramid bind:this={components[depth]} data={d} {form} params={page.params} {error} />
				{/if}
			</svelte:boundary>
		{/snippet}

		{@render pyramid(0)}
	`;

	write_if_changed(
		`${output}/root.svelte`,
		dedent`
			<!-- This file is generated by @sveltejs/kit — do not edit it! -->
			<svelte:options runes={true} />
			<script>
				import { afterNavigate } from '$app/navigation';

				let { page, constructors, components = [], form, errors = [], error, ${levels
					.map((l) => `data_${l} = null`)
					.join(', ')} } = $props();
				let data = $derived({${levels.map((l) => `'${l}': data_${l}`).join(', ')}});

				let mounted = $state(false);
				let navigated = $state(false);
				let title = $state(null);

				afterNavigate(() => {
					if (mounted) {
						navigated = true;
						title = document.title || 'untitled page';
					} else {
						mounted = true;
					}
				});

				const Pyramid_${max_depth} = $derived(constructors[${max_depth}]);
			</script>

			${pyramid}

			{#if mounted}
				<div id="svelte-announcer" aria-live="assertive" aria-atomic="true" style="position: absolute; left: 0; top: 0; clip: rect(0 0 0 0); clip-path: inset(50%); overflow: hidden; white-space: nowrap; width: 1px; height: 1px">
					{#if navigated}
						{title}
					{/if}
				</div>
			{/if}
		`
	);

	write_if_changed(
		`${output}/root.js`,
		dedent`
		import { asClassComponent } from 'svelte/legacy';
		import Root from './root.svelte';
		export default asClassComponent(Root);
	`
	);
}
