import fs from 'node:fs';
import path from 'node:path';
import { styleText } from 'node:util';
import { posixify } from '../../utils/os.js';
import { read_package_imports, normalize_import_value } from '../../utils/imports.js';
import { write_if_changed } from './utils.js';
import { exclude } from 'rolldown/filter';

/**
 * @param {string} cwd
 * @param {string} file
 */
function maybe_file(cwd, file) {
	const resolved = path.resolve(cwd, file);
	if (fs.existsSync(resolved)) {
		return resolved;
	}
}

/**
 * @param {string} cwd
 * @param {string} file
 */
function project_relative(cwd, file) {
	return posixify(path.relative(cwd, file));
}

/**
 * @param {string} file
 */
function remove_trailing_slashstar(file) {
	if (file.endsWith('/*')) {
		return file.slice(0, -2);
	} else {
		return file;
	}
}

/**
 * Generates the tsconfig that the user's tsconfig inherits from.
 * @param {import('types').ValidatedKitConfig} kit
 * @param {string} root
 */
export function write_tsconfig(kit, root) {
	const out = path.join(root, 'node_modules/$app/tsconfig/tsconfig.json');

	const user_config = load_user_tsconfig(root);
	if (user_config) validate_user_config(user_config);

	write_if_changed(out, JSON.stringify(get_tsconfig(out, kit, root), null, '\t'));
}

/**
 * Generates the tsconfig that the user's tsconfig inherits from.
 * @param {string} out The file we're writing to
 * @param {import('types').ValidatedKitConfig} kit
 * @param {string} cwd
 */
export function get_tsconfig(out, kit, cwd) {
	/** @param {string} file */
	const config_relative = (file) => posixify(path.relative(path.dirname(out), file));

	const config = {
		compilerOptions: {
			paths: get_tsconfig_paths(kit, cwd),
			rootDirs: [config_relative('.'), config_relative(`${kit.outDir}/types`)],
			types: ['$app/types'],

			// essential options
			// svelte-preprocess cannot figure out whether you have a value or a type, so tell TypeScript
			// to enforce using \`import type\` instead of \`import\` for Types.
			// Also, TypeScript doesn't know about import usages in the template because it only sees the
			// script of a Svelte file. Therefore preserve all value imports.
			verbatimModuleSyntax: true,
			// Vite compiles modules one at a time
			isolatedModules: true,

			// recommended options
			allowJs: true,
			checkJs: true,
			forceConsistentCasingInFileNames: true,
			resolveJsonModule: true,

			// This is required for svelte-package to work as expected
			// Can be overwritten
			lib: ['esnext', 'DOM', 'DOM.Iterable'],
			moduleResolution: 'bundler',
			module: 'esnext',
			noEmit: true, // prevent tsconfig error "overwriting input files" - Vite handles the build and ignores this
			target: 'esnext'
		},
		exclude: [
			config_relative(
				path.extname(kit.files.serviceWorker)
					? kit.files.serviceWorker
					: `${kit.files.serviceWorker}/**`
			)
		]
	};

	return kit.typescript.config(config) ?? config;
}

/** @param {string} cwd */
function load_user_tsconfig(cwd) {
	const file = maybe_file(cwd, 'tsconfig.json') || maybe_file(cwd, 'jsconfig.json');

	if (!file) return;

	// we have to eval the file, since it's not parseable as JSON (contains comments)
	const json = fs.readFileSync(file, 'utf-8');

	return {
		kind: path.basename(file),
		options: (0, eval)(`(${json})`)
	};
}

/**
 * @param {{ kind: string, options: any }} config
 */
function validate_user_config(config) {
	// we need to check that the user's tsconfig extends the framework config
	const extend = config.options.extends;
	const extends_framework_config =
		typeof extend === 'string'
			? extend === '$app/tsconfig'
			: Array.isArray(extend)
				? extend.includes('$app/tsconfig')
				: false;

	const options = config.options.compilerOptions || {};

	if (extends_framework_config) {
		const { paths, baseUrl } = options;

		// TODO: baseUrl will be removed in TypeScript 7.0
		if (baseUrl || paths) {
			console.warn(
				styleText(
					['bold', 'yellow'],
					`You have specified a baseUrl and/or paths in your ${config.kind} which interferes with SvelteKit's auto-generated tsconfig.json. ` +
						'Remove it to avoid problems with intellisense. For path aliases, use `config.alias` instead: https://svelte.dev/docs/kit/configuration#alias'
				)
			);
		}
	} else {
		console.warn(
			styleText(
				['bold', 'yellow'],
				`Your ${config.kind} should extend the configuration generated by SvelteKit:`
			)
		);
		console.warn(`{\n  "extends": "$app/tsconfig"\n}`);
	}
}

// <something><optional /*>
const alias_regex = /^(.+?)(\/\*)?$/;
// <path><optional /* or .fileending>
const value_regex = /^(.*?)((\/\*)|(\.\w+))?$/;

/**
 * Generates tsconfig path aliases from kit's aliases and the package.json `imports` field.
 * Related to vite alias creation.
 *
 * @param {import('types').ValidatedKitConfig} config
 * @param {string} cwd
 */
function get_tsconfig_paths(config, cwd) {
	/** @param {string} file */
	const config_relative = (file) => {
		let relative_path = path.relative(config.outDir, file);
		if (!relative_path.startsWith('..')) {
			relative_path = './' + relative_path;
		}
		return posixify(relative_path);
	};

	const alias = { ...config.alias };

	// Add all `#`-prefixed imports from package.json as path aliases
	const imports = read_package_imports(cwd);
	if (imports) {
		for (const [key, raw_value] of Object.entries(imports)) {
			if (!key.startsWith('#')) continue;
			const value = normalize_import_value(raw_value);
			if (value) {
				alias[key] = value;
			}
		}
	}

	/** @type {Record<string, string[]>} */
	const paths = {};

	for (const [key, value] of Object.entries(alias)) {
		const key_match = alias_regex.exec(key);
		if (!key_match) throw new Error(`Invalid alias key: ${key}`);

		const value_match = value_regex.exec(value);
		if (!value_match) throw new Error(`Invalid alias value: ${value}`);

		const rel_path = config_relative(remove_trailing_slashstar(value));
		const slashstar = key_match[2];

		if (slashstar) {
			paths[key] = [rel_path + '/*'];
		} else {
			paths[key] = [rel_path];
			const fileending = value_match[4];

			if (!fileending && !(key + '/*' in alias)) {
				paths[key + '/*'] = [rel_path + '/*'];
			}
		}
	}

	return paths;
}
