import { Adapter } from '@sveltejs/kit';

export interface AdapterOptions {
	/** The directory to write prerendered pages to. It defaults to `build`. */
	pages?: string;
	/**
	 * The directory to write static assets (the contents of `static`, plus client-side JS and CSS generated by SvelteKit) to. Ordinarily this should be the same as `pages`, and it will default to whatever the value of `pages` is, but in rare circumstances you might need to output pages and assets to separate locations.
	 */
	assets?: string;
	/**
	 * To create a [single page app (SPA)](https://svelte.dev/docs/kit/single-page-apps) you must specify the name of the fallback page to be generated by SvelteKit, which is used as the entry point for URLs that have not been prerendered. This is commonly `200.html`, but can vary depending on your deployment platform. You should avoid `index.html` where possible to avoid conflicting with a prerendered homepage.
	 *
	 * > [!NOTE] This option has large negative performance and SEO impacts. It is only recommended in certain circumstances such as wrapping the site in a mobile app. See the [single page apps](https://svelte.dev/docs/kit/single-page-apps) documentation for more details and alternatives.
	 */
	fallback?: string;
	/**
	 * If `true`, precompresses files with brotli and gzip. This will generate `.br` and `.gz` files.
	 */
	precompress?: boolean;
	/**
	 * By default, `adapter-static` checks that either all pages and endpoints (if any) of your app were prerendered, or you have the `fallback` option set. This check exists to prevent you from accidentally publishing an app where some parts of it are not accessible, because they are not contained in the final output. If you know this is ok (for example when a certain page only exists conditionally), you can set `strict` to `false` to turn off this check.
	 */
	strict?: boolean;
}

export default function plugin(options?: AdapterOptions): Adapter;
