import Root from '__GENERATED__/root.svelte';
// @ts-expect-error - doesn't exist yet. generated by Rollup
import { routes, fallback } from '__GENERATED__/manifest.js';
import { set_paths } from '../paths.js';
import { Prefetcher } from './prefetcher.js';
import { Router } from './router.js';
import { Renderer } from './renderer.js';
import { init } from './singletons.js';

/**
 * @param {{
 *   paths: {
 *     assets: string;
 *     base: string;
 *   },
 *   target: Node;
 *   session: any;
 *   route: boolean;
 *   spa: boolean;
 *   trailing_slash: import('types').TrailingSlash;
 *   hydrate: {
 *     status: number;
 *     error: Error;
 *     nodes: Array<Promise<import('types').CSRComponent>>;
 *     params: Record<string, string>;
 *   };
 * }} opts
 */
export async function start({ paths, target, session, route, spa, trailing_slash, hydrate }) {
	const renderer = new Renderer({
		Root,
		fallback,
		target,
		session
	});

	let router = null;
	let prefetcher;
	if (route) {
		router = new Router({
			base: paths.base,
			routes,
			trailing_slash,
			renderer
		});
		prefetcher = new Prefetcher({ router, handle_prefetch: renderer.load.bind(renderer) });
	}

	init({ prefetcher, router, renderer });
	set_paths(paths);

	if (hydrate) await renderer.start(hydrate);
	if (router) {
		if (spa) router.goto(location.href, { replaceState: true }, []);
		router.init_listeners();
		prefetcher?.init_listeners();
	}

	dispatchEvent(new CustomEvent('sveltekit:start'));
}
