// @ts-expect-error - doesn't exist yet. generated by Rollup
import Root from 'ROOT';
// @ts-expect-error - doesn't exist yet. generated by Rollup
import { routes, fallback } from 'MANIFEST';
import { Router } from './router.js';
import { Renderer } from './renderer.js';
import { init } from './singletons.js';
import { set_paths } from '../paths.js';

/**
 * @param {{
 *   paths: {
 *     assets: string;
 *     base: string;
 *   },
 *   target: string;
 *   session: any;
 *   host: string;
 *   route: boolean;
 *   spa: boolean;
 *   trailing_slash: import('types/internal').TrailingSlash;
 *   hydrate: {
 *     status: number;
 *     error: Error;
 *     nodes: Array<import('types/internal').CSRComponent>;
 *     legacy_nodes: Array<import('types/internal').CSRComponent>;
 *     page: import('types/page').Page;
 *   };
 * }} opts
 */
export async function start({ paths, target, session, host, route, spa, trailing_slash, hydrate }) {
	if (import.meta.env.DEV && !target) {
		throw new Error('Missing target element. See https://kit.svelte.dev/docs#configuration-target');
	}

	const renderer = new Renderer({
		Root,
		fallback,
		target: document.querySelector(target) ?? document.body,
		session,
		host
	});

	const router = route
		? new Router({
				base: paths.base,
				routes,
				trailing_slash,
				renderer
		  })
		: null;

	init(router);
	set_paths(paths);

	if (hydrate) {
		if (import.meta.env.LEGACY) {
			hydrate.nodes = hydrate.legacy_nodes;
		}

		hydrate.nodes = await Promise.all(hydrate.nodes.map((n) => import(/* @vite-ignore */ n)));
		hydrate.page.query = new URLSearchParams(hydrate.page.query);

		await renderer.start(hydrate);
	}

	if (router) {
		if (spa) router.goto(location.href, { replaceState: true }, []);
		router.init_listeners();
	}

	dispatchEvent(new CustomEvent('sveltekit:start'));
}
