// generated by `adapt` in the output directory
declare module '#@sveltejs/adapter-bun' {
	export const server: import('@sveltejs/kit').Server;
	/** the output directory */
	export const dir: string;
	export const app_dir: string;
	export const base: string;
	/** assets are embedded in an executable and imported by identity path */
	export const embed: boolean;
	export const env_prefix: string;
	export const origin: string | undefined;
	export const server_options: Pick<
		import('bun').Serve.Options<never>,
		| 'development'
		| 'hostname'
		| 'port'
		| 'idleTimeout'
		| 'maxRequestBodySize'
		| 'reusePort'
		| 'unix'
		| 'ipv6Only'
	>;
	/** `[helper, url, file, meta]`, where `file` is an embedded asset or a path below `dir` */
	export const assets: Array<
		[
			'client_asset' | 'prerendered_asset' | 'prerendered_page',
			string,
			string,
			{ hash: string; mtime: number; br?: boolean; gz?: boolean }
		]
	>;
	/** `[url, status, location]` */
	export const redirects: Array<[string, number, string]>;
	/** `[file, embedded asset]` */
	export const server_assets: Array<[string, string?]>;
}
