<!-- This file is generated by @sveltejs/kit — do not edit it! -->
<script>
	import { setContext, afterUpdate } from 'svelte';
	import { Layout, ErrorComponent } from './manifest.js';

	// error handling
	export let status = undefined;
	export let error = undefined;

	export let stores;
	export let segments;
	export let level0;
	export let level1 = null;
	export let notify;

	afterUpdate(notify);
	setContext('__svelte__', stores);
</script>

{#if error}
	<ErrorComponent {status} {error}/>
{:else}
	<Layout segment={segments[0]} {...level0.props}>
		<svelte:component this={level1.component} {...level1.props}/>
	</Layout>
{/if}