// this file is a placeholder `$types` module that exists purely for typechecking the codebase.
// in actual use, the `$types` module will be declared in an ambient module generated by
// SvelteKit into `.svelte-kit/types`
export interface RouteIds {}
