import { Adapter } from '@sveltejs/kit';
import './ambient.d.ts';

/** A Node.js runtime supported by Netlify. */
export type Runtime = 'nodejs22.x' | 'nodejs24.x';

export type AdapterOptions = {
	/**
	 * If `true`, your app will be split into multiple functions instead of a single one for the entire app.
	 * @default false
	 */
	split?: boolean;
	/**
	 * The directory to write prerendered pages and static assets (the contents of `static`, plus client-side JS and CSS generated by SvelteKit) to.
	 * @default 'build'
	 * @since 7.0.0
	 */
	publish?: string;
} & (
	| {
			/**
			 * Deploy your app as [Netlify Edge Functions](https://docs.netlify.com/build/edge-functions/overview/) rather than Node-based functions.
			 * Edge Functions run in a Deno-based environment and cannot use a Node.js `runtime`.
			 */
			edge: true;
			runtime?: undefined;
	  }
	| {
			/**
			 * Deploy your app as Node-based functions rather than [Netlify Edge Functions](https://docs.netlify.com/build/edge-functions/overview/).
			 * @default false
			 */
			edge?: false;
			/**
			 * The [Node.js version for the runtime](https://docs.netlify.com/build/functions/configuration/#nodejs-version-for-runtime), for example `nodejs24.x`.
			 * Specifying this option selects Node-based functions and cannot be combined with `edge: true`.
			 * @default Same as the Netlify build environment
			 */
			runtime?: Runtime | undefined;
	  }
);

export default function plugin(opts?: AdapterOptions): Adapter;
