import { Adapter } from '@sveltejs/kit';
import './ambient.d.ts';

/** A Node.js runtime supported by Netlify. */
export type Runtime = 'nodejs22.x' | 'nodejs24.x';

export type Config =
	| {
			/**
			 * Deploy this route as a [Netlify Edge Function](https://docs.netlify.com/build/edge-functions/overview/).
			 * Set `nodeVersion: undefined` to clear a Node runtime inherited from a layout.
			 */
			edge: true;
			nodeVersion?: undefined;
	  }
	| {
			/**
			 * Set `false` to deploy this route as a Node-based function, overriding an Edge adapter or layout.
			 */
			edge?: false;
			/**
			 * Which [Serverless Function](https://docs.netlify.com/build/functions/configuration/#nodejs-version-for-runtime)
			 * Node.js version to use (`'nodejs22.x'` or `'nodejs24.x'`).
			 * Set `undefined` to clear a version inherited from a layout and use the adapter default.
			 * @default Same as the adapter
			 */
			nodeVersion?: Runtime | undefined;
	  };

export type AdapterOptions = {
	/**
	 * If `true`, your app will be split into multiple functions instead of a single one for the entire app.
	 * @default false
	 */
	split?: boolean;
	/**
	 * The directory to write prerendered pages and static assets (the contents of `static`, plus client-side JS and CSS generated by SvelteKit) to.
	 * @default 'build'
	 * @since 7.0.0
	 */
	publish?: string;
} & (
	| {
			/**
			 * If `true`, your app will be deployed as a [Netlify Edge Function](https://docs.netlify.com/build/edge-functions/overview/) rather than the standard Node-based function.
			 * Cannot be combined with the `nodeVersion` option.
			 */
			edge: true;
			nodeVersion?: undefined;
	  }
	| {
			/**
			 * If `true`, your app will be deployed as a [Netlify Edge Function](https://docs.netlify.com/build/edge-functions/overview/) rather than the standard Node-based function.
			 * @default false
			 */
			edge?: false;
			/**
			 * The [Node.js version](https://docs.netlify.com/build/functions/configuration/#nodejs-version-for-runtime) used for the serverless function. The supported values are `'nodejs22.x'` and `'nodejs24.x'`.
			 * Cannot be combined with `edge: true`.
			 */
			nodeVersion?: Runtime | undefined;
	  }
);

export default function plugin(opts?: AdapterOptions): Adapter;
