name: 'Node Setup'
description: 'Set up the repo and run it on Node.js'

inputs:
  node-version:
    description: 'The Node version to install'
    required: true
    default: '24'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
