name: 'Node Setup'
description: 'Set up the repo and run it on Node.js'

inputs:
  node-version:
    description: 'The Node version to install'
    required: true
    default: '24'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
      with:
        runtime: node@${{ inputs.node-version }}
        cache: true
