name: 'Node Setup'
description: 'Set up the repo and run it on Node.js'

inputs:
  node-version:
    description: 'The Node version to install'
    required: true
    default: '24'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
      with:
        runtime: node@${{ inputs.node-version }}
        cache: true
