name: audit

on:
  schedule:
    - cron: "0 5 * * *" # daily 5AM

env:
  # not needed for audit
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  Audit:
    # prevents this action from running on forks
    if: github.repository == 'sveltejs/kit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/node-setup
      # check prod dependencies as these would affect users
      - run: pnpm audit --prod
