name: audit

on:
  schedule:
    - cron: '0 5 * * *' # daily 5AM

env:
  # not needed for audit
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  Audit:
    # prevents this action from running on forks
    if: github.repository == 'sveltejs/kit'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/node-setup
      # check prod dependencies as these would affect users
      - run: pnpm audit --prod
