name: Benchmarks

on:
  push:
    branches:
      - version-3
    paths-ignore: &paths_ignore
      - '.changeset/**'
      - '.githooks/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/copilot-instructions.md'
      - '.github/FUNDING.yml'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - 'documentation/**'
      - 'packages/*/CHANGELOG*.md'
      - 'packages/kit/src/types/synthetic/**'
      - 'AGENTS.md'
      - 'CLAUDE.md'
      - 'CONTRIBUTING.md'
      - 'FUNDING.json'
      - 'LICENSE'
      - 'README.md'
      - '.coderabbit.yml'
  pull_request:
    paths-ignore: *paths_ignore
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: codspeed-macro
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/node-setup
      - name: Run benchmarks
        uses: CodSpeedHQ/action@373d6868929f444bc08d901fd0eb0ad52a8875ea # v5.2.1
        with:
          mode: walltime
          run: pnpm bench
