name: Platform Tests (Vercel)

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Commit SHA to test'
        required: false
        default: ''
  workflow_call:
    inputs:
      sha:
        description: 'Commit SHA to test'
        required: false
        type: string
        default: ''

permissions:
  contents: read

jobs:
  basic:
    if: github.repository == 'sveltejs/kit'
    uses: ./.github/workflows/platform-test-vercel.yml
    with:
      sha: ${{ inputs.sha || github.sha }}
      variant: basic
      test-app-dir: packages/adapter-vercel/test/apps/basic
      purge-cache: true

  split:
    if: github.repository == 'sveltejs/kit'
    uses: ./.github/workflows/platform-test-vercel.yml
    with:
      sha: ${{ inputs.sha || github.sha }}
      variant: split
      test-app-dir: packages/adapter-vercel/test/apps/split
