name: Platform Tests (Vercel)

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Commit SHA to test'
        required: false
        default: ''
  workflow_call:
    inputs:
      sha:
        description: 'Commit SHA to test'
        required: false
        type: string
        default: ''

permissions:
  contents: read

env:
  PLATFORM: vercel
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  build-basic:
    if: github.repository == 'sveltejs/kit'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      VARIANT: basic
      TEST_APP_DIR: packages/adapter-vercel/test/apps/basic
    steps: &build-steps
      - &checkout-actions
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.workflow_sha }}
          persist-credentials: false
          sparse-checkout: |
            .github/actions
            pnpm-lock.yaml
          path: .workflow

      - uses: ./.workflow/.github/actions/vercel-build
        with:
          sha: ${{ inputs.sha || github.sha }}
          test-app-dir: ${{ env.TEST_APP_DIR }}
          variant: ${{ env.VARIANT }}

  build-split:
    if: github.repository == 'sveltejs/kit'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      VARIANT: split
      TEST_APP_DIR: packages/adapter-vercel/test/apps/split
    steps: *build-steps

  deploy-basic:
    if: github.repository == 'sveltejs/kit'
    needs: build-basic
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: '@sveltejs/adapter-vercel platform tests'
    env:
      VARIANT: basic
    steps:
      - *checkout-actions
      - uses: ./.workflow/.github/actions/vercel-deploy
        with:
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_BASIC }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          purge-cache: true

  deploy-split:
    if: github.repository == 'sveltejs/kit'
    needs: build-split
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: '@sveltejs/adapter-vercel platform tests'
    env:
      VARIANT: split
    steps:
      - *checkout-actions
      - uses: ./.workflow/.github/actions/vercel-deploy
        with:
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_SPLIT }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}

  test-basic:
    if: github.repository == 'sveltejs/kit'
    needs: deploy-basic
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      VARIANT: basic
      TEST_APP_DIR: packages/adapter-vercel/test/apps/basic
    steps: &test-steps
      - *checkout-actions
      - uses: ./.workflow/.github/actions/platform-test
        with:
          sha: ${{ inputs.sha || github.sha }}

  test-split:
    if: github.repository == 'sveltejs/kit'
    needs: deploy-split
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      VARIANT: split
      TEST_APP_DIR: packages/adapter-vercel/test/apps/split
    steps: *test-steps
