name: Release

on:
  push:
    branches:
      - version-3

concurrency:
  # prevent two release workflows from running at once
  # race conditions here can result in releases failing
  group: ${{ github.workflow }}

permissions: {}
jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'sveltejs/kit'
    permissions:
      contents: write # to create release (changesets/action)
      id-token: write # OpenID Connect token needed for provenance
      pull-requests: write # to create pull request (changesets/action)
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
        with:
          runtime: node@24
          # don't cache pnpm for releases to circumvent cache poisoning
          cache: false

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@22ccf9aa43179fe9e27dc62e575971d28cce197c # v2.0.0
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish-script: pnpm changeset:release
          version-script: pnpm changeset:version
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # TODO alert discord
      # - name: Send a Slack notification if a publish happens
      #   if: steps.changesets.outputs.published == 'true'
      #   # You can do something when a publish happens.
      #   run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
