/** @import { Message } from '@sveltejs/message-box' */
import fs from 'node:fs';
import { parse, render } from '@sveltejs/message-box';

const messages_dir = new URL('../../messages/', import.meta.url);
const templates_dir = new URL('./templates/', import.meta.url);
const output_dir = new URL('../../src/messages/', import.meta.url);

const banner = '/* This file is generated by scripts/process-messages/index.js. Do not edit! */';

/** @type {Set<string>} */
const seen = new Set();

for (const category of fs.readdirSync(messages_dir).sort()) {
	if (category.startsWith('.')) continue;

	/** @type {Message[]} */
	const messages = [];

	for (const file of fs.readdirSync(new URL(`${category}/`, messages_dir)).sort()) {
		if (!file.endsWith('.md')) continue;

		const markdown = fs
			.readFileSync(new URL(`${category}/${file}`, messages_dir), 'utf-8')
			.replace(/\r\n/g, '\n');

		for (const message of parse(markdown)) {
			if (seen.has(message.code)) {
				throw new Error(`Duplicate message code ${category}/${message.code}`);
			}

			seen.add(message.code);
			messages.push(message);
		}
	}

	messages.sort((a, b) => (a.code < b.code ? -1 : a.code > b.code ? 1 : 0));

	const template = fs
		.readFileSync(new URL(`${category}.js`, templates_dir), 'utf-8')
		.replace(/\r\n/g, '\n')
		.trim();

	// leading import lines are emitted once at the top of the generated module
	const lines = template.split('\n');
	let i = 0;
	while (i < lines.length && /^(import |\/\*\* @import )/.test(lines[i])) i += 1;
	const preamble = lines.slice(0, i).join('\n');
	const body = lines.slice(i).join('\n').trim();

	const output = messages.map((message) => render(message, body)).join('\n\n');

	fs.mkdirSync(output_dir, { recursive: true });
	fs.writeFileSync(
		new URL(`${category}.js`, output_dir),
		`${banner}\n\n${preamble ? `${preamble}\n\n` : ''}${output}\n`
	);
}
